### ISSUE TITLE
Begin Android testing

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#119]
Someone with an Android, make you the app works fine on the Expo emulator.
Android has NEVER been tested before, this is the initial test.
We want to Beta on Android soon. Two people could work together on this.
If something is broken, open a new issue and report it so that we can fix it.

**You may encounter errors at first!**

- [ ] Run nuMom on Android using Expo Emulator.
- [ ] Report any issues on Github.
- [ ] Build Android APK file.

If so, please build the APK file using `expo build:android` and upload the APK file here.

**Comment by edumorlom** [comment]
How to build with Expo:
https://docs.expo.io/distribution/building-standalone-apps/

**Comment by lchik001** [comment]
Testing on SM-G975U - Samsung Galaxy S10+ 
Android Version 10
Kernel Version: 4.14.117-19529858

Let me know if you need more software information.

I'll keep anything else I find in a file and upload that later to avoid having too many comments on here if we run into a lot of issues, but just an issue I've had for a while concerning swiping up to sign up. 

After successfully swiping up, the confetti animation makes my phone screen blink in the colors of the confetti. Nothing app breaking but just a visual glitch that maybe we could address. 

A bigger problem is that Leo and I both experience some lag and slowdown with the swipe and vibration feedback, especially for Leo.

**Comment by LeonelADiaz** [comment]
View the following link for the APK file as it was too large to attach: https://www.dropbox.com/s/omeq6dec3codt86/MomsInfantsAndroidAPK.zip?dl=0

**Comment by lchik001** [comment]
Here are the issues we were able to find running on a few different Android devices.

[android_tests.pdf](https://github.com/edumorlom/moms-infants-healthy/files/5314346/android_tests.pdf)

**Comment by LeonelADiaz** [comment]
Feature complete.
