### ISSUE TITLE
Missing Translations in Creole

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#120]
Go into the Creole .json file and report any missing translations so that I can send them over to Jean.
Missing translations are those that are in English but not in Creole.

All I need is the English text. For example:

"Log In", "Create an Account", "Password"...

- [x] Get missing translations.
- [x] Update app to reflect new translations.

**Comment by lchik001** [comment]
Hey Eduardo,

I see there are two JSON files for the English phrases, en_STD and en_US. en_STD is all translated in ht_STD, so we just need all the phrases in en_US translated. You just want me to list all those phrases out in a comment here right? Just making sure I'm not overthinking things here.

**Comment by edumorlom** [comment]
`You just want me to list all those phrases out in a comment here right?`
Correct, I just need the missing translations from en_US. You can post them here.

**Comment by edumorlom** [comment]
My bad, I thought the creole translations were already pushed.
Leave this issue on standby.

**Comment by edumorlom** [comment]
Below are some creole translations. Some are missing. Please report the ones missing so we can get those translated.
[Content NuMom Translation (Hadassah Coriolan)  (3).docx](https://github.com/edumorlom/moms-infants-healthy/files/5319360/Content.NuMom.Translation.Hadassah.Coriolan.3.docx)

**Comment by lchik001** [comment]
As part of this issue would you like us to start adding the available translations into the ht_HT.json file or keep that separate?

**Comment by edumorlom** [comment]
please add them to ht_HT.json

**Comment by Mhyma004** [comment]
test

**Comment by Society9** [comment]
I added the translations in the doc file supplied and made a pull request. These are the remaining phrases that still need
translating.

    "Shelters",
    "Call Clinic",
    "Carefully open and remove female condom from package to prevent tearing.",
    "The thick, inner ring with closed end is used for placing in the vagina and holds condom in place. The thin, outer ring remains outside of body, covering vaginal opening.",
    "Find a comfortable position. While holding outside of condom at closed end, squeeze sides of inner ring together with your thumb and forefinger and insert into vagina. It is similar to inserting a tampon.",
    "Using your finger, push inner ring as far up as it will go until it rests against cervix. The condom will expand naturally, and you may not feel it.",
    "Be sure condom is not twisted. The thin, outer ring should remain outside vagina.",
    "Guide partner’s penis into opening of female condom. Stop intercourse if you feel penis slip between condom and walls of vagina or if outer ring is pushed into vagina.",
    "To remove, gently twist outer ring and pull female condom out of vagina.",
    "Throw away female condom in trash after using it one time. Do not reuse.",
    "Female Condom Do's and Don’ts",
    "DO use a female condom from start to finish, every time you have vaginal sex.*",
    "DO read the condom package insert and check the expiration date.",
    "DO make sure there are no tears or defects.",
    "DO use lubricant to help prevent the condom from slipping and tearing.",
    "DO store female condoms in a cool, dry place.",
    "DON’T use a male condom with a female condom, as this can cause tearing.",
    "DON’T reuse a female condom.",
    "DON’T flush female condoms as they may clog the toilet.",
    "The female condom is a protection barrier method of birth control. It can reduce the chance of becoming pregnant or getting Sexually transmitted Disease (STDs).",
    "How To Insert and Remove a Female Condom",
    "Female Condom",
    "Protected Sex",
    "Protect yourself and have a safe time",
    "Time",
    "Date",
    "Reference",
    "Reference your Doctor or Medical Specialties",
    "Add Reference",
    "Name of Reference",
    "Phone of Reference",
    "Email of Reference",
    "Medical Specialties",
    "Remove The Reference",
    "Are you sure want to remove this reference?",
    "Send an email",
    "Make a call",
    "Name",
    "Specialties",
    "Phone",
    "Email",
    "Distance",
    "Abortions", 
    "Pregnancy Tests",
    "Support & Counseling",
    "Education",
    "Medical Care",
    "Lab services",
    "Pharmacy",
    "Family Planning",
    "Immunization",
    "Free Materials",
    "Ultrasound",
    "Referrals",
    "Sonograms",
    "STD Tests",
    "STD Treatment",
    "Medicaid Assistance",
    "Food Stamps",
    "Yearly Exam",
    "Emergency Testing",
    "Miles"

**Comment by edumorlom** [comment]
Thanks!
