### ISSUE TITLE
Move all STD translations to the main translation files.

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#126]
Currently we have two translation files per language.
For example english has : en_US and en_STD.

https://github.com/edumorlom/moms-infants-healthy/blob/master/src/Components/getLocalizedText.js

I think it's best if we keep all translations in one file.
Could someone migrate all the STD translations to the main es_ES, en_US translation.

This requires changing to getLocalizedText works.

**Comment by lchik001** [comment]
Do you want me to rename ht_STD to something like ht_HT for now? Then we can use that as the main translation file moving forward?

**Comment by edumorlom** [comment]
yes please
  
  
  
  
  
  
  
  
  
  

  
  
Eduardo Morales
  
 Software Engineer
  
  
  

  
  
  
  
  

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
 +1 (786) 715-4286 (tel:+1+(786)+715-4286)
  
  
  
  
  
  
  

  
  
  
  
  
 edmorales.97@gmail.com (mailto:edmorales.97@gmail.com)
  
  
  
  
  
  
  

  
  
  
  
  
 https://edumorales.dev (https://edumorales.dev/)
  
  
  
  
  
  
  

  
  
  
  
  
Miami, FL
  
  
  
  
  
  
  
  
  
  
  
  

  
  
>
