### ISSUE TITLE
Add logos to clinics

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#129]
I'm not sure what the best way to do this is, but Jean would like to add logos to the site.
There should be a property to the Firebase Clinics db that includes a path to the logo or image.

If there is no logo, show the pink + sign otherwise.
Also, make sure the logos fit and look good. So we might need to use an outside library to format the image. It should look professional.

Ping me if you have any questions.

**Comment by LeonelADiaz** [comment]
Completed and merged.

**Comment by LeonelADiaz** [comment]
Completed and merged.
