### ISSUE TITLE
CSS Property causes "Swipe Up To Sign Up" to move with keyboard.

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#132]
"Swipe Up To Sign Up" should not move if the keyboard is displayed.
It should always stay at the bottom center.

Maybe the CSS property should be **positioned absolutely.**

![image](https://user-images.githubusercontent.com/11444894/94968942-d5677280-04cf-11eb-8c69-06e591d3aa1d.png)

**Comment by edumorlom** [comment]
Can be closed?

**Comment by LeonelADiaz** [comment]
Feature was merged.
