### ISSUE TITLE
Remove top label from Settings text boxes

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#140]
In an effort to make Settings look a lot more like Sign Up, please remove the top label from the text boxes.

See image below:

![IMG_665618B51310-1](https://user-images.githubusercontent.com/11444894/95263384-b5032500-07fb-11eb-9390-1b3d32dbb163.jpeg)

**Comment by PantherDave** [comment]
I removed the top text labels from the settings screen, but does the screen say "Setting" or "Settings"?

**Comment by edumorlom** [comment]
It says "Settings" this is an old image.

**Comment by PantherDave** [comment]
Awesome
