### ISSUE TITLE
Change colors of Map Pins

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#149]
Currently we are using a red and blue for Clinics and Shelters pins.

Let's switch the colors to:
Clinics: nuMom Pink
Shelters: nuMom Blue

Look at the Styles in the code for the exact HEX code. If you have a question, please don't hesitate to ask!

![image](https://user-images.githubusercontent.com/11444894/95414306-93896280-08fb-11eb-9727-ea966b816d27.png)

**Comment by edumorlom** [comment]
@jgonz11 This was merged already right?

**Comment by edumorlom** [comment]
If so, can be closed.

**Comment by LeonelADiaz** [comment]
Feature complete.
