### ISSUE TITLE
Change STD Awareness icon change

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#156]
Change the STD Awareness Logo in Learn to the following.

![icons8-pink-ribbon-100](https://user-images.githubusercontent.com/11444894/95521803-72c31a80-0998-11eb-9ced-90c2cce4212b.png)

**Comment by PantherDave** [comment]
I changed the STD Awareness Logo on the branch stdAwarenessLogo and removed the top text labels on Settings on topTextLabel branch.

**Comment by LeonelADiaz** [comment]
Feature completed.
