### ISSUE TITLE
Change filter and unfilter icons

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#158]
Change the filter and unfilter icons. We might change them again in the future.

![icons8-filter-100](https://user-images.githubusercontent.com/11444894/95522466-2f69ab80-099a-11eb-8352-41f0bd2e97e8.png)

![unfilter](https://user-images.githubusercontent.com/11444894/95522619-8a9b9e00-099a-11eb-8adc-49a169083320.png)

**Comment by LeonelADiaz** [comment]
Feature completed.
