### ISSUE TITLE
Signing-up Existing Email->Shows Alert but doesn't go to the Original Signup State 

### ISSUE THREAD

**Issue by rolyGit** [edumorlom/moms-infants-healthy#170]

**Comment by edumorlom** [comment]
How do I reproduce this?

**Comment by rolyGit** [comment]
> How do I reproduce this?

You create a testing account with let's say email test@yahoo.com (no interested in other fields), then logout and try to signup as a new user with the same email address test@yahoo.com. The app will show an error alert saying that the email is already associated with another account, then when you click ok the app crashes(expected behavior->go to original signup state)

**Comment by edumorlom** [comment]
For me it hangs on the homepage, it goes through the DNI animation, logs you in and hangs on the map view. I was able to reproduce. Thanks!

**Comment by rolyGit** [comment]
> For me it hangs on the homepage, it goes through the DNI animation, logs you in, and hangs on the map view. I was able to reproduce. Thanks!

I'm still reviewing this issue... I have not found the right way to fix it. Any feedback on this???

**Comment by edumorlom** [comment]
My solution would be to use Firebase API to check if the email already exists.
If it exists, prevent the user from continuing. Otherwise, continue.
