### ISSUE TITLE
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component/> from render.

### ISSUE THREAD

**Issue by LeonelADiaz** [edumorlom/moms-infants-healthy#175]
Currently, attempting to create a new appointment or reference yields a blank page and throws the above error.
![d67384aa85e653de5a77416b998a8cd0](https://user-images.githubusercontent.com/9453556/96077261-4e29df80-0e7d-11eb-9dd4-a9070e32f024.png)

**Comment by edumorlom** [comment]
Will look into it as well.

**Comment by LeonelADiaz** [comment]
Warning no longer persists, will close unless problem arises again.
