### ISSUE TITLE
Screen Transition Overhaul

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#176]
Currently transitioning from screens is very messy. Specially in the LowerPanel.

We need to come up with a new way that is a lot more simple. I can brainstorm with whoever takes on the task.

**Comment by LeonelADiaz** [comment]
> 
> 
> is this still in progress?

We're wrapping up soon. All the transitions from (LogIn -> Homepage -> Everywhere else) is complete. All that's left are UI fixes, and finalizing the transitions in Sign-Up.

**Comment by LeonelADiaz** [comment]
Feature merged and complete.
