### ISSUE TITLE
Unify "Clinics" and "Shelters" into 1

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#177]
We only want three buttons on the Main Screen:
1. Facilities
2. Learn
3. Resources

When the user clicks on Facilities:
1. Clinics
2. Shelters
**3. I forget the third one?**

**Comment by edumorlom** [comment]
![Uploading IMG_3F72EDB78BB9-1.jpeg…]()

**Comment by edumorlom** [comment]
![IMG_3F72EDB78BB9-1](https://user-images.githubusercontent.com/11444894/96078739-2b99c580-0e81-11eb-8f5e-ac0ae733f857.jpeg)

**Comment by lchik001** [comment]
We'll probably need a logo for the Facilities tab unless you want to reuse something we already have.

**Comment by edumorlom** [comment]
We can re-use the clinics logo, i will find another one in the meantime.

**Comment by jgonz11** [comment]
![facilities](https://user-images.githubusercontent.com/50336804/96748314-5c08c480-1397-11eb-9cd2-48fc4d8b8b8a.jpeg)

**Comment by LeonelADiaz** [comment]
Closed as the feature has been implemented and merged.
