### ISSUE TITLE
In-app Notifications for infants and appointments

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#178]
Jean wanted notifications that originate from the app that alert the user of:

1) Their upcoming appointments that they had created in the appointments tab
2) Information concerning the infant they added to the app. What information she wanted I'm not too sure as I assumed she would provide any relevant medical information

The alert should be on iOS the little red number that you can see from the home screen, and also pop up notifications that happen on either device

**Comment by LeonelADiaz** [comment]
@hchu004 Could you post what you were able to wrap up? You were only able to complete part 1 right?

**Comment by gravy-davy** [comment]
Push notifications for appointments have been completed using expo-notifications. #303

**Comment by joselo09111** [comment]
Push notifications for appointments have been completed using firebase's expo-notifications
