### ISSUE TITLE
Center DNA image

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#182]
The loading gif should be centered **vertically**, for some reason it has been moved.

![IMG_9313](https://user-images.githubusercontent.com/11444894/96396673-bafeeb80-1195-11eb-83e6-2fe13b1c6031.PNG)

**Comment by LeonelADiaz** [comment]
> 
> 
> i forget, was this fixed?

Was mainly working on the screens transitions as I wanted that to have higher priority. Once I'm done with the screen transitions (definitely by next Friday) I'll sort this one out. Sorry for the delay!

**Comment by LeonelADiaz** [comment]
Feature completed, will close.
