### ISSUE TITLE
Swipe up to Sign Up should be lowered

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#183]
The swipe up to sign up should be lowered and placed on the white area.
Currently it's on top of the blue, which causes a rendering issue.

![IMG_CD6148F613EB-1](https://user-images.githubusercontent.com/11444894/96396815-0ca77600-1196-11eb-8d18-547b418134e7.jpeg)

**Comment by LeonelADiaz** [comment]
Feature completed. Will reopen if formatting did not help.

**Comment by LeonelADiaz** [comment]
Feature completed. Will reopen if formatting did not help.

**Comment by edumorlom** [comment]
mmmh i dont think formatting did anything

**Comment by edumorlom** [comment]
![IMG_A5E1F07E79AA-1](https://user-images.githubusercontent.com/11444894/98450712-e9c10f80-210c-11eb-88fd-54fee3837aa5.jpeg)

**Comment by LeonelADiaz** [comment]
We'll take another look at it. Sorry about that!

**Comment by LeonelADiaz** [comment]
Feature working and merged, will close.
