### ISSUE TITLE
Baby Immunization Register

### ISSUE THREAD

**Issue by LeonelADiaz** [edumorlom/moms-infants-healthy#185]
Rolando suggested the following feature to be added to the NuMom app. It has been approved by Jean and we can begin work on it. Please view the following document Rolando provided for a detailed explanation on what is to be expected.

https://docs.google.com/document/d/1ZaR8N-xcZiQmZkZdg4ssDs3gmYUF8jeU6oSUstG8cDE/edit?usp=sharing

**Comment by edumorlom** [comment]
I like 👍  Thanks for the suggestion
