### ISSUE TITLE
Center loading gif.

### ISSUE THREAD

**Issue by LeonelADiaz** [edumorlom/moms-infants-healthy#192]
Currently the loading gif is shown as below. It would be great if it was a bit smaller and centered.

![4f60007b3cc565faea4659dcbb23718d](https://user-images.githubusercontent.com/9453556/97035459-5a283800-1534-11eb-85fc-39899fb34b17.png)

**Comment by PantherDave** [comment]
![109C61BF-4753-404B-A2FE-3CDB43B51791](https://user-images.githubusercontent.com/39570366/97053665-5b1b9280-1551-11eb-9a8e-4a2ad58eb048.png)
Is this any better?

**Comment by LeonelADiaz** [comment]
> 
> 
> ![109C61BF-4753-404B-A2FE-3CDB43B51791](https://user-images.githubusercontent.com/39570366/97053665-5b1b9280-1551-11eb-9a8e-4a2ad58eb048.png)
> Is this any better?

Looks good! @edumorlom good to go?

**Comment by LeonelADiaz** [comment]
Feature completed and merged.
