### ISSUE TITLE
Search develop for any missing translations.

### ISSUE THREAD

**Issue by LeonelADiaz** [edumorlom/moms-infants-healthy#211]
New pushes are being made to develop and we want to make sure that anything the user is able to read is being translated currently for their device. This will be an on-going issue as new features are about to be pushed and merged, so during your time, just look through the code and find anything missing a translation.

**Comment by lchik001** [comment]
[Missing translations.docx](https://github.com/edumorlom/moms-infants-healthy/files/5550309/Missing.translations.docx)

I believe these are all the missing translations in develop now. Will need the Spanish and Creole translations of these when possible.

**Comment by LeonelADiaz** [comment]
@lchik001 Were you able to get the translations?

**Comment by lchik001** [comment]
Sorry, not sure how I missed it but there are additional missing Creole translations from line 151 - 191 in the ht_HT.json file. Will have to leave this for whoever is working on this next year.

**Comment by LeonelADiaz** [comment]
Feature merged and completed.
