### ISSUE TITLE
Go Back button text on iOS

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#217]
Can we change the text color to match the icon? We can do any of the following:

1. font color to pink.
3. Remove text
2. use native iOS icon

![IMG_2A4A8AC047A2-1](https://user-images.githubusercontent.com/11444894/98450764-6d7afc00-210d-11eb-8dba-b1c028240a9e.jpeg)

**Comment by LeonelADiaz** [comment]
Added a snippet to remove the text on iOS. Please verify that it hides it as I can't test it on Android. Thanks!

**Comment by edumorlom** [comment]
mmmh doesnt seem to be fixed, the other option is.

Can we remove the icon and instead just change the font color to pink?

**Comment by edumorlom** [comment]
How does it look on Android

**Comment by LeonelADiaz** [comment]
It doesn't show the previous screen's name in the left side of the header, its just the arrow there. I'll try looking into other possible solutions for it.

**Comment by LeonelADiaz** [comment]
Feature merged and completed.
