### ISSUE TITLE
Forgot password UI changes

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#218]
This screen is ugly ugly.

1. Remove the "Please enter the e-mail associated with your account" text.
2. Change the "Send" button to say "Reset Password".
3. Lower button to match "Next"  buttons during Sign up.

![IMG_E6B6C52A1A74-1](https://user-images.githubusercontent.com/11444894/98450808-de221880-210d-11eb-85f9-efd656e5cbeb.jpeg)

**Comment by LeonelADiaz** [comment]
![Screenshot_20201108-122658_Expo](https://user-images.githubusercontent.com/9453556/98472044-46c8ce00-21be-11eb-9417-6e9f09d1af97.jpg)

@edumorlom

**Comment by edumorlom** [comment]
great thanks!

**Comment by LeonelADiaz** [comment]
Feature completed and merged.
