### ISSUE TITLE
[Firebase] Your Realtime Database 'numom-57642' has insecure rules

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#230]
I keep getting this e-mail twice a day, and it's getting annoying so might as well fix it :)

![image](https://user-images.githubusercontent.com/11444894/99762192-f0b13000-2ac5-11eb-839b-a3537b0084b1.png)

**Comment by Supercala155** [comment]
Updated the Security rules so that users can only read and write their own data. Seems to work with no issues.

**Comment by edumorlom** [comment]
Awesome! thanks

**Comment by edumorlom** [comment]
Can close, will let you know if I get any other emails
