### ISSUE TITLE
Swipe up to Sign Up is difficult

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#264]
Currently, swiping up requires you to swipe up from the swipe up arrow. It is a bit hard sometimes, I've noticed.

1. The goal should be to be able to swipe up from any point of the bottom half of the screen.
2. Clicking on the circle, should also take you to the swipe up page.

**Comment by Supercala155** [comment]
Pull request for swiping up issue had been merged,
