### ISSUE TITLE
Settings: Disappear keyboard on click of screen

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#266]
Currently, in settings, it's impossible to make the keyboard disappear.
Clicking anywhere on the screen should make the keyboard disappear.

Look at the code in the Sign Up pages to give you an idea. The keyboard disappears in the Sign Up pages.

![IMG_FBAD8BACC39D-1](https://user-images.githubusercontent.com/11444894/119082430-1616ec00-b9cc-11eb-893f-bce5ecc2b6d7.jpeg)

**Comment by gravy-davy** [comment]
Feature complete and merged.
