### ISSUE TITLE
Settings: Change logout icon and align it properly.

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#268]
![IMG_4111](https://user-images.githubusercontent.com/11444894/119082470-2f1f9d00-b9cc-11eb-96ed-2f6b0a4df690.jpg)

1. Change the logout icon to the following icon. It is a bit thicker.
2. Align the logout icon with the go back icon.

![logout](https://user-images.githubusercontent.com/11444894/119083493-07c9cf80-b9ce-11eb-8533-d4c5a686f271.png)

**Comment by Supercala155** [comment]
Merged to Development.
