### ISSUE TITLE
Replace let with const

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#292]
Any time a variable is not re-assigned, the variable should be declared using `const`.

Go through the entire code, on the terminal, you can use this command `grep -r "let " .` inside the `moms-infants-healthy/src/Components`.

This will display everywhere `let` is used. Your job is to replace any variables that don't get resigned to use `const` instead of let.

You may be able to use a Linting tool that might tell you when a variable is re-assigned or not.

**Comment by NathalyS19** [comment]
Issue is completed and has been merged into development.
