### ISSUE TITLE
Ensure setting an appointment is working.

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#293]
<img width="1468" alt="Screen Shot 2021-06-06 at 9 07 08 PM" src="https://user-images.githubusercontent.com/11444894/120946657-2983c000-c70b-11eb-8e3b-b2103e249d54.png">
The feature might not be fully finished.
Ensure that creating a new appt is working, and if it's not, please get it to work.

This requires some back-end work in Firebase.

**Comment by gravy-davy** [comment]
Creating an appointment works as intended.
