### ISSUE TITLE
Incorrect Sign Up Behavior

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#294]
https://user-images.githubusercontent.com/11444894/121563320-4c9ec000-c9e8-11eb-8d3c-42b7b0e40271.MP4

Current Behavior:
1. Swipe up to sign up
2. At the confetti screen, click on the "back arrow".
3. After a few seconds, it will take  you to "Do you live in Miami?"

Expected Behavior:
1. Swipe up to sign up
2. At the confetti screen, click on the "back arrow".
3. It should not take you to do the "Do you live in Miami" screen if you have clicked on "Go Back".
The reasoning is that you have already left the Sign Up process.

**Comment by Supercala155** [comment]
Pull request created under "Corrected Sign Up Behavior", awaiting merge to development.
