### ISSUE TITLE
Lower Swipe Up To Sign Up

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#295]
Swipe up to sign up is too high up.
It should be lowered.

Maybe positioned 5% from bottom.

<img width="415" alt="Screen Shot 2021-06-10 at 12 39 33 PM" src="https://user-images.githubusercontent.com/11444894/121564100-157cde80-c9e9-11eb-9153-2159d46841be.png">

**Comment by Supercala155** [comment]
Merged to Development.
