### ISSUE TITLE
Forgot password: Use the language json text for "invalid e-mail".

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#297]
![IMG_45474A0AF8EF-1](https://user-images.githubusercontent.com/11444894/121564807-da2edf80-c9e9-11eb-9461-f10cfddd4f6a.jpeg)

Use the language JSON text for "invalid e-mail". Same for other languages.

<img width="726" alt="Screen Shot 2021-06-10 at 12 47 51 PM" src="https://user-images.githubusercontent.com/11444894/121565039-14987c80-c9ea-11eb-9847-818ca32161a9.png">

**Comment by Supercala155** [comment]
Merged to Development.
