### ISSUE TITLE
Information in WIC Feeding section is a clickable when it shouldn't be

### ISSUE THREAD

**Issue by Supercala155** [edumorlom/moms-infants-healthy#325]
In Resources, under WIC, in the Feeding Section, the information provided for each of the months is clickable, and results in the error "props.onPress is not a function. (In 'props.onPress()', 'props.onPress' is null)". From what I can tell, the information should just be shown without being able to be clicked.

Please make these buttons unclickable, or make clicking them not cause an error.

**Comment by julianlopez6850** [comment]
This issue was fixed with the merge of PR #343 into development
