### ISSUE TITLE
Upgrade to Expo 42: window.navigator.geolocation.getCurrentPosition is not available

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#329]
After upgrading to Expo 42 branch. I see the following error:
Let's switch our project to https://docs.expo.io/versions/latest/sdk/location/
This will fix many of ours new issues.

![IMG_BB1E85A23693-1](https://user-images.githubusercontent.com/11444894/127064339-e4f6d63c-231e-4c13-aee9-412365f91ca1.jpeg)

**Comment by edumorlom** [comment]
window.navigator.geolocation.getCurrentPosition is not available. Import and execute installWebGeolocationPolyfill() from expo-location to add it, or use the expo-location APIs instead.

**Comment by OscarHSanchez108** [comment]
I no longer receive this issue when I test the upgrade to Expo 42 branch. I think we can close this issue now.

**Comment by Supercala155** [comment]
This issue was fixed during the technical meeting and has been merged already.
