### ISSUE TITLE
Upgrade to Expo 42: requestPermissionsAsync() is Deprecated

### ISSUE THREAD

**Issue by lroche823** [edumorlom/moms-infants-healthy#336]
When I try to open the app I recieve this error alongside the app crashing immediately.
I believe this issue is related to #329 as the deprecated method is mentioned here in the Location documentation: [link](https://docs.expo.dev/versions/latest/sdk/location/) 
![Screenshot_20210906-134352_Expo Go](https://user-images.githubusercontent.com/89804525/132578105-2a466173-a197-44ea-8e1d-482313338bc3.jpg)

**Comment by edumorlom** [comment]
fixed.
