### ISSUE TITLE
Upgrade to Expo42: AsyncStorage is null.

### ISSUE THREAD

**Issue by fany19** [edumorlom/moms-infants-healthy#340]
To fix this issue try these steps:

  • Run `react-native link @react-native-community/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-community.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

**Comment by edumorlom** [comment]
Async Storage has moved to new organization: https://github.com/react-native-async-storage/async-storage

**Comment by edumorlom** [comment]
The way to fix this is to replace all async storages with the new library

**Comment by edumorlom** [comment]
fixed.
