### ISSUE TITLE
Upgrade to Expo42: Unable to resolve module '@react-native-async-storage/async-storage' ...

### ISSUE THREAD

**Issue by julianlopez6850** [edumorlom/moms-infants-healthy#341]
This issue would occur before the app would finish building.
![image](https://user-images.githubusercontent.com/66705096/133170015-99b6d526-235e-45ce-9f83-f5d9db68786e.png)

### To fix this issue, try these steps (they resolved the issue on my end):

1. `rm -rf node_modules`

2. `yarn install`

3. `yarn start --reset-cache`

On this step, I received this message: 

> error: unknown option `--reset-cache'

so I don't know if the `--reset-cache` makes any difference

4. `rm -rf /tmp/metro-cache/`

5. Finally, run `expo start` and rebuild the app as you normally would.

These steps are a slight change to the recommended steps in the screenshot. If they don't work, maybe try the steps in the screenshot exactly as they are given.

### After I ran these steps, the app finished building and opened successfully. Several new issues occurred, and it looked like this:
![image](https://user-images.githubusercontent.com/66705096/133170668-82760b04-24ee-4ece-8486-df1af4e02820.png)

**Comment by edumorlom** [comment]
The steps given in #334 should have made you delete your node_modules.
Can confirm if the first issue happens again? I think the issue is that you had the old node_modules installed. 
Did you delete node_modules before installing SDK 42?

**Comment by julianlopez6850** [comment]
> 
> 
> The steps given in #334 should have made you delete your node_modules.
> Can confirm if the first issue happens again? I think the issue is that you had the old node_modules installed.
> Did you delete node_modules before installing SDK 42?

You're right. I just tested it. I guess I forgot to delete the old node_modules prior to installing sdk 42. Thanks for the help.
