### ISSUE TITLE
Add another dropdown that allows the user to pick first dose, second dose, etc...

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#353]
![IMG_1FCB91F1AD9D-1](https://user-images.githubusercontent.com/11444894/135758350-3de6dac0-d524-4132-b3fc-30082a0a045c.jpeg)

Currently, we have pre-set "First dose polio", "Second dose polio", etc...

Instead there should be two dropdowns:
First: Vaccine Type.
Second: First, second, third, fourth Shot.

**Comment by edumorlom** [comment]
Also remove <<>> from Select Immunization.

**Comment by julianlopez6850** [comment]
This was completed when PR #358 merged
