### ISSUE TITLE
Resources Tab: WIC and Medicaid Locations

### ISSUE THREAD

**Issue by kimbob138** [edumorlom/moms-infants-healthy#386]
Within this tab it offers to apply to WIC or Medicaid and to look at locations. Once the user reaches this page, there is a big block of grey speace, and no filter icon for the user to filter through locations and try to find a location near them. Nor are the sections titled. 
![IMG_1540](https://user-images.githubusercontent.com/97994738/151480914-fb1e7f0e-4e03-4c19-b355-257dcf96d802.PNG)
![IMG_1539](https://user-images.githubusercontent.com/97994738/151480934-df956f5c-7996-4b21-85c4-5ba46ea1f703.PNG)

**Comment by julianlopez6850** [comment]
The grey space on these pages has been fixed, as per issue #427 and PR #444. I will make a new Issue asking to include a filter for these pages.
