### ISSUE TITLE
Text cuts off in Female Condom section

### ISSUE THREAD

**Issue by gabegomez000** [edumorlom/moms-infants-healthy#393]
If you go to "Learn" -> "Protected Sex" -> "How to Insert and Remove a Female Condom," 
the end of the text on the third step is cut off and hard to read:

![Screenshot_20220211-111340_Expo_Go](https://user-images.githubusercontent.com/68518672/153627701-807fba82-b8ab-4018-bb96-e96ebc2fe9c6.jpeg)

**Comment by aqibshah96** [comment]
Evidence that issue #393 is also addressed in this PR 
![IMG_3305](https://user-images.githubusercontent.com/105533928/202932474-b6c0f23a-c6cc-4de6-b5c3-901046ca9e2f.PNG)
