### ISSUE TITLE
Change size of rectangular buttons housing options on Learn page 

### ISSUE THREAD

**Issue by aqibshah96** [edumorlom/moms-infants-healthy#485]
Change size of rectangular buttons housing options on Learn page 

![IMG_2394](https://user-images.githubusercontent.com/105533928/173263490-66b52dfc-5bcb-4509-a6cf-ab99416983d7.PNG)

**Comment by Hana091285** [comment]
![buttons](https://user-images.githubusercontent.com/68342404/174893486-f9ab3b68-5186-438a-a1db-e3dd10e4a765.jpeg)
