### ISSUE TITLE
Validated emails

### ISSUE THREAD

**Issue by Hana091285** [edumorlom/moms-infants-healthy#487]
The application requires to enter the contact information(email address & Phone Number). I have tried to register with my two validated emails but the alert message shows that the emails that have been entered are not validated. Also I have tried a random not validated email and it allowed me to register.
the alert message should pop either that the email has already been used or that the email is not validated for real.

![Image 2022-06-16 at 4 39 26 PM](https://user-images.githubusercontent.com/68342404/174160783-876d22af-7c31-4123-b2e6-20674377a0d3.jpeg)
![Image 2022-06-16 at 4 40 52 PM](https://user-images.githubusercontent.com/68342404/174160785-5f9867ce-0c69-444a-b5a4-e0ce2df2bad3.jpeg)

**Comment by edumorlom** [comment]
Can someone reproduce this issue?

**Comment by Hana091285** [comment]
> Can someone reproduce this issue?

i have post it this issue, what do you mean by reproducing it?
