### ISSUE TITLE
Improve password screen feedback (weak password)

### ISSUE THREAD

**Issue by MasterShakezula** [edumorlom/moms-infants-healthy#592]
Improve responses from the password screen when a weak password is provided when making a new account.

For example, if the user provides a poor strength password, they will receive a pop-up warning "Password does not match". Instead, the warning should warn the user that their password is too weak and is not valid.

![580e8212-18d6-4ef1-91ee-64dc1725a8b7](https://user-images.githubusercontent.com/90061079/218293136-1520ca01-ab55-4a90-9e0f-5dca85bde9bf.jpeg)

Above, the password in both boxes are the same. So the warning is inaccurate.

**Comment by daviddelgadol** [comment]
During my testing, this issue cannot be replicated using the Development branch. This issue may have appeared after the completion of the Task password strength checker, as this modification can be seen on the screenshot.

**Comment by vroja035** [comment]
PR #690
