### ISSUE TITLE
Add Date of Birth restrictions on sign-up page

### ISSUE THREAD

**Issue by MasterShakezula** [edumorlom/moms-infants-healthy#600]
When making an account, the user is able to select a date, month, and/or year in the future as their date of birth and proceed making their account.

For example, they could choose 12/31/2050 or 12/31/2023 as their date of birth and still be allowed to continue. They are only stopped if they put in the year 2100 or higher.

Add restrictions so that the user may not choose a day, month, or year in the future as their date of birth.

**Comment by JosephBargallo** [comment]
Issue has been completed. Users will no longer be allowed to proceed when entering a future date for their date of birth.

**Comment by JosephBargallo** [comment]
Issue has been completed. Users will no longer be allowed to proceed when entering a future date for their date of birth.
