### ISSUE TITLE
Fix word/letter spacing for the relevant information sections in the Feeding page.

### ISSUE THREAD

**Issue by miguelSablan** [edumorlom/moms-infants-healthy#607]
The spacing for some of the words and letters look very off and inconsistent, the words should be more compact and consistent.

![image](https://user-images.githubusercontent.com/57413108/226073438-56de4cd7-4279-4689-85a8-ef311a7aeaef.png)
![image](https://user-images.githubusercontent.com/57413108/226073444-59bea6fc-d2c1-4041-8142-0c0c070b5511.png)
![image](https://user-images.githubusercontent.com/57413108/226073451-d0a3f402-8346-4658-92d9-796a1ec8d641.png)

**Comment by JosephBargallo** [comment]
Issue had been completed
