### ISSUE TITLE
Stop the user from being logged out when they press the previous page button (mobile)

### ISSUE THREAD

**Issue by MasterShakezula** [edumorlom/moms-infants-healthy#610]
https://user-images.githubusercontent.com/90061079/226508534-bf040698-7517-4bd4-beea-a2567feca803.mp4

When logged in, if the user is at the home screen of the app and hits the previous button on their phone, they'll be returned to the log in screen and essentially "logged out". This is somewhat jarring and inconvenient for the user's experience. 

Try to find a solution so that if a user is logged in, they will not be thrown back to the login screen by just hitting the previous page button while on the home page.

**Comment by JosephBargallo** [comment]
Issue completed.

- Back button does not log user out anymore
