### ISSUE TITLE
Problem validating fields in app.json.

### ISSUE THREAD

**Issue by probycode** [edumorlom/moms-infants-healthy#632]
![image](https://github.com/edumorlom/nuMom/assets/18001053/5d709e8c-1226-4d97-889b-49772897dbe6)

Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android - should NOT have additional property 'useNextNotificationsApi'.

**Comment by JosephBargallo** [comment]
Pull request has been reviewed and merged for this issue
