### ISSUE TITLE
Profile Editing Visual Issue/Inconsistency

### ISSUE THREAD

**Issue by vroja035** [edumorlom/moms-infants-healthy#678]
On the profile editing page, when choosing an answer for the questions "Are you pregnant?" and "Do You Have Any Infants?" the answer choices do not fully display, "Yes" displays as "Y..." and "No" displays as "...".

![WhatsApp Image 2023-08-30 at 1 09 16 PM](https://github.com/edumorlom/nuMom/assets/105022916/0b9df5e4-e245-4887-bd3f-ac43080634eb)

**Comment by vroja035** [comment]
**Might only be an issue for Android devices.

**Comment by edumorlom** [comment]
I think you can fix this by changing the width and making it larger.
