### ISSUE TITLE
Drop down menu gets too high

### ISSUE THREAD

**Issue by JoseBaez010** [edumorlom/moms-infants-healthy#687]
For some reason when you pick '20 miles' and then try to change it back to 'All' the drop-down menu gets super high up and makes it impossible for you to click on it.

These two are super high up:
![IMG_3365](https://github.com/edumorlom/nuMom/assets/83191691/563360b9-1a94-49e9-b734-ad6c486dec55)
![IMG_3364](https://github.com/edumorlom/nuMom/assets/83191691/e261d703-8918-4d03-99ed-78204092c532)

This is what it should be like for all the options:
![IMG_3367](https://github.com/edumorlom/nuMom/assets/83191691/ad05b8d9-92f1-4d5f-ab8d-ac63a3d5fbcc)

**Comment by vroja035** [comment]
This doesn't seem to be an issue anymore.
