### ISSUE TITLE
Fix Phone Number Formatting on References Page

### ISSUE THREAD

**Issue by vroja035** [edumorlom/moms-infants-healthy#693]
Fix the formatting on the references tab so that the phone number displays in (###) ### - #### format.

![image](https://github.com/edumorlom/nuMom/assets/105022916/e1b3442c-56db-4e17-af85-41943f4c58fd)

**Comment by fernandoapem** [comment]
Formatting was fixed on a previous commit, closing issue
<img width="350" alt="Screenshot 2024-05-14 at 1 12 32 PM" src="https://github.com/edumorlom/nuMom/assets/61566161/b2f7557b-315a-4e97-9114-77cfa605286b">
