### ISSUE TITLE
Female Condoms

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#70]
[Female condom ENGLISH(2).docx](https://github.com/edumorlom/moms-infants-healthy/files/4854175/Female.condom.ENGLISH.2.docx)
[Female condom Spanish june 2(2).docx](https://github.com/edumorlom/moms-infants-healthy/files/4854176/Female.condom.Spanish.june.2.2.docx)
[Female condom Creole june 2(2).docx](https://github.com/edumorlom/moms-infants-healthy/files/4854177/Female.condom.Creole.june.2.2.docx)

**Comment by edumorlom** [comment]
Reopening. Please add the following translations for Female Condom.

**Comment by lchik001** [comment]
Quick question @edumorlom for the Spanish translations, there are two different translations for FemaleCondomHowTo. 

Cómo insertar y quitar un condón femenino

Cómo colocar y retirar el condón femenino

Which one do you think I should keep?

**Comment by edumorlom** [comment]
Cómo colocar y retirar el condón femenino

That seems to be the latin american translation. Thanks.

**Comment by LeonelADiaz** [comment]
Feature complete.
