### ISSUE TITLE
Scrolling through clinics/shelter ends too early

### ISSUE THREAD

**Issue by jocelyndr** [edumorlom/moms-infants-healthy#701]
For my case (iphone 14)
Not sure if other phone sizes are affected.

When clicking into clinics or shelters, I am able to scroll all the way to the bottom of the list, however, there are still clinics/shelters at the bottom but the scroll feature ends before the list ends.

The screenshots attached will show you where the scrolling stops. The non-visible clinics/shelters are highlighted.
![IMG_1801](https://github.com/edumorlom/nuMom/assets/95481049/2be12e34-5a80-4eb1-b938-061e67e5c124)
![IMG_1802](https://github.com/edumorlom/nuMom/assets/95481049/f9bbf6bd-aea8-4d0e-b243-4c136a6c33f8)

**Comment by edumorlom** [comment]
I think its the same as #702
