### ISSUE TITLE
Change input text color on add references page

### ISSUE THREAD

**Issue by jocelyndr** [edumorlom/moms-infants-healthy#717]
When I go to add a reference, the text in the input box is very hard to read.
![IMG_2457](https://github.com/edumorlom/nuMom/assets/95481049/721c1222-7079-41ac-8481-b1f42a77aa4c)

**Comment by fernandoapem** [comment]
Issue has been already resolved, closing issue
| Text with input     | Text with no input |
| -------- | ------- |
| ![Simulator Screenshot - iPhone 14 Pro - 2024-05-14 at 12 38 52](https://github.com/edumorlom/nuMom/assets/61566161/d2b91d31-156a-4301-bbb1-7469e03d4647)  | ![Simulator Screenshot - iPhone 14 Pro - 2024-05-14 at 12 37 26](https://github.com/edumorlom/nuMom/assets/61566161/ff24da5a-4f0f-4497-8e0c-be17dd762801)   |
