### ISSUE TITLE
Add a reference to the fields that are not visible to identify what should be put into them

### ISSUE THREAD

**Issue by JoseBaez010** [edumorlom/moms-infants-healthy#718]
For some reason the letters are barely visibly to tell which section is which
![81faac6f-4364-4f49-9284-004f4aa96019](https://github.com/edumorlom/nuMom/assets/83191691/0f172312-db30-4f52-bc86-48a27abf681f)

**Comment by fernandoapem** [comment]
Same issue as #717 
Closing as it is resolved when running the app.
