### ISSUE TITLE
Upgrade to SDK 50

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#722]

**Comment by fernandoapem** [comment]
Upgraded to 51.0

**Comment by fernandoapem** [comment]
Closing issue
<img width="729" alt="Screenshot 2024-05-14 at 1 08 28 PM" src="https://github.com/edumorlom/nuMom/assets/61566161/22788bd7-3541-4968-9b67-183bcd2634ff">
